name: Build
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: write
  actions: read
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: gradle/actions/setup-gradle@v3
      - run: make test
